<?php
/**
 * @file
 * Code for the CA Products feature.
 */

include_once 'ca_products.features.inc';

/**
 * Implements hook_menu().
 */
function ca_products_menu() {
  $items['admin/config/worx_features/product'] = array(
    'title' => 'Product Configuration',
    'description' => 'Override settings for ca_products',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ca_products_settings_form'),
    'access arguments' => array('worx features admin'),
    'file' => 'ca_products.admin.inc',
    'file path' => drupal_get_path('module', 'ca_products'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/config/worx_features/product/general'] = array(
    'title' => 'General Settings',
    'description' => 'Override settings for ca_products',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ca_products_settings_form'),
    'access arguments' => array('worx features admin'),
    'file' => 'ca_products.admin.inc',
    'file path' => drupal_get_path('module', 'ca_products'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );

  return $items;
}

/**
 * Implements hook_menu_alter().
 */
function ca_products_menu_alter(&$items) {
  $items['products']['title'] = variable_get('ca_products_menu_title', 'Products');
}

/**
 * Implements hook_panels_pre_render().
 */
function ca_products_panels_pre_render($panel, $renderer) {
  foreach ($panel->content as $key => $value) {
    if ($value->subtype == 'ca_products_list-ca_products_category_list_1') {
      $panel->title = variable_get('ca_products_panel_title', 'Products');
    }
  }
}

/**
 * Implements hook_views_pre_render().
 */
function ca_products_views_pre_view(&$view, &$display_id, &$args) {
  if ($display_id == 'ca_products_category_list_1') {
    $view->set_items_per_page(variable_get('ca_products_cat_list_count', 20));
  }
  if ($display_id == 'ca_products_sub_cat_list_one') {
    $view->set_items_per_page(variable_get('ca_products_sub_cat_list_count', 4));
  }
  if ($display_id == 'ca_products_product_list_1') {
    $view->set_items_per_page(variable_get('ca_products_list_count', 10));
  }
  elseif ($display_id == 'ca_products_block_1') {
    $view->set_items_per_page(variable_get('ca_products_block_count', 1));
  }
  if ($display_id == 'ca_products_product_grid') {
    $view->set_items_per_page(variable_get('ca_products_list_count', 10));
  }
}

/**
 * Implementation of hook_ctools_plugin_directory()
 */
function ca_products_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools') {
    return 'plugins/' . $plugin_type;
  }
}

/**
 * Implements hook_token_info().
 */
function ca_products_token_info() {
  
  // Define token value, product_category_hierarchy is the token will be used as [node:product_category_hierarchy]
  $data['tokens']['node']['product_category_hierarchy'] = array(
    'name' => t("Product category hierarchy"),
    'description' => t("Hierachy path of the category"),
  );
  
  // Define token value, product_product_path is the token will be used as [node:product_product_path]
  $data['tokens']['node']['product_product_path'] = array(
    'name' => t("Product product path"),
    'description' => t("The path of the category the product is located at"),
  );
  
  // Return associative array of tokens & token types
  return $data;
}

/**
 * Implements hook_tokens().
 */
function ca_products_tokens($type, $tokens, array $data = array(), array $options = array()) {
  $replacements = array();

  // Check if token type is node
  if($type == 'node'){
    foreach ($tokens as $name => $original) {
      switch ($name) {
        // Check token is product_category_hierarchy
        case 'product_category_hierarchy':
          $cateparent =  $data['node']->field_ca_category_parent;
          //print_r($data['node']);
          $search  = array(' w/', '/');
          $replace = array(' ', '-');
          if ($cateparent[LANGUAGE_NONE] != NULL) {
            $x = $cateparent[LANGUAGE_NONE][0]['target_id'];
            while ($x > 0) {
              $node = node_load($x);
              $nodetitlefix = str_replace($search, $replace, $node->title);
              if (isset($replacements[$original])) {
                $replacements[$original] = $nodetitlefix . '/' . $replacements[$original];
              } else {
                $replacements[$original] = $nodetitlefix;
              }
              //print_r('Category Path ' . $replacements[$original]);
              $cateparent =  $node->field_ca_category_parent;
              //print_r('Category Parent ' . $cateparent);
              if ($cateparent != NULL) {
                $x = $cateparent[LANGUAGE_NONE][0]['target_id'];
              } else {
                break;
              }
            }
          }
          //print_r('Category Path ' . $replacements[$original]);
          break;
        // Check token is product_product_path
        case 'product_product_path':
          $category =  $data['node']->field_ca_product_parent_category[LANGUAGE_NONE][0]['target_id'];
          //print_r($data['node']);
          $nodepath = 'node/' . $category;
          $path = drupal_get_path_alias($nodepath);
          //print_r($path);
          $replacements[$original] = $path;
          break;
      }
    }
  }
  return $replacements;
}