<?php

/**
 * Implementation of hook_install().
 */
function ca_products_install() {
  variable_set('ca_products_category_list_template', 'ca_products_category_list_template_one');
  variable_set('ca_products_category_node_template', 'ca_products_category_node_template_one');
  variable_set('ca_products_product_node_template', 'ca_products_product_node_template_one');
}

/**
 * Implementation of hook_uninstall().
 */
function ca_products_uninstall() {
  variable_del('ca_products_category_list_template');
  variable_del('ca_products_category_node_template');
  variable_del('ca_products_product_node_template');
}
